from diffusers import StableDiffusionPipeline
import torch
import os
from PIL import ImageDraw, ImageFont

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

prompt = input("Enter your prompt: ")

with torch.autocast("cuda"):
    img = pipe(prompt).images[0]

draw = ImageDraw.Draw(img)
text = "Generated by Stable Diffusion"
font = ImageFont.load_default()
bbox = draw.textbbox((0, 0), text, font=font)
text_width = bbox[2] - bbox[0]
x = (img.width - text_width) // 2
y = 10
draw.text((x + 1, y + 1), text, font=font, fill=(0, 0, 0))
draw.text((x, y), text, font=font, fill=(255, 255, 255))

os.makedirs("result", exist_ok=True)
img.save("result/output.png")
print("Image saved to result/output.png")
